# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-26 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0002_auto_20160626_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='infosword',
            name='mFrench',
            field=models.CharField(default=b'false', max_length=200),
        ),
    ]
