# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameCountry', models.CharField(max_length=100)),
                ('flagCountry', models.CharField(max_length=50)),
                ('imgCountry', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=5)),
                ('month', models.CharField(max_length=20)),
                ('nameImage', models.CharField(max_length=100)),
                ('legendImage', models.TextField(blank=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelapp.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namePlace', models.CharField(max_length=100)),
                ('latPlace', models.CharField(max_length=100)),
                ('longPlace', models.CharField(max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelapp.Country')),
            ],
        ),
        migrations.AddField(
            model_name='picture',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelapp.Place'),
        ),
    ]
