# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='slugCountry',
            field=models.SlugField(default='default_slug', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='slugPlace',
            field=models.SlugField(default='default_place', max_length=100),
            preserve_default=False,
        ),
    ]
